<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_length2" value="0.05"/>
    <xacro:property name="lidar_radius2" value="0.05"/>
 

    <link name="lidar_link2">

            <visual>
                <geometry>
                    <cylinder radius="${lidar_radius2}" length="${lidar_length2}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${lidar_radius2}" length="${lidar_length2}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />            
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2*lidar_radius2}" h="${2*lidar_length2}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />    

     </link>

     <joint name="base_lidar_joint2" type="fixed">
         <parent link="lidar_link"/>
         <child link="lidar_link2" />
         <origin xyz="0 0 ${lidar_length2 + 0.01}" rpy="0 0 0 " />
     </joint>


    <gazebo reference="lidar_link2">
        <material>Gazebo/Red</material> 
        <self_collide>false</self_collide>
        <sensor type="ray" name="head_hokuyo_sensor1">
             <pose>10 0 10 0 0 0</pose>
             <visualize>false</visualize>
             <update_rate>30</update_rate>
            <ray>
             <scan>
              <horizontal>
                <samples>720</samples>
                <resolution>1</resolution>
                <min_angle>-3.14</min_angle> 
                <max_angle>3.14</max_angle>  
               </horizontal>
              </scan>
               <range>
                    <min>0.10</min>
                    <max>10.0</max>
                   <resolution>0.01</resolution>
                 </range>
                 <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                 </noise>
            </ray>
            <plugin name="gazebo_ros_ray_sensor2" filename="libgazebo_ros_ray_sensor.so">
                   <topic_name>/scan</topic_name>
                   <frame_name>lidar_link2</frame_name>
                   <output_type>sensor_msgs/LaserScan</output_type>
            </plugin>


        </sensor>

    </gazebo>



</robot>