# Default initial positions for my_robot's ros2_control fake system

initial_positions:
  base_left_wheel_joint: 0
  base_right_wheel_joint: 0
  elbow_joint: 0
  shoulder_lift_joint: 0
  shoulder_pan_joint: 0
  wrist_1_joint: 0
  wrist_2_joint: 0
  wrist_3_joint: 0